part of educ_memory_game;

//Following include modifications by Alain Castonguay and Marie-Helene Dore
var imageList = [
                 'bishop.jpg',
                 'brown.jpg',
                 'capilano.jpg',
                 'cornell.jpg', 
                 'crandall.jpg',
                 'duke.jpg',
                 'fraser.jpg',
                 'georgetown.jpg',
                 'guelph.jpg',
                 'harvard.jpg',
                 'johnshopkins.jpg',
                 'laval.jpg',
                 'manitoba.jpg',
                 'mcgill.jpg',
                 'miami.jpg',
                 'mit.jpg',
                 'northwestern.jpg',
                 'notredame.jpg',
                 'nyu.jpg',
                 'ottawa.jpg',
                 'princeton.jpg', 
                 'queen.jpg',
                 'stanford.jpg',
                 'toronto.jpg',
                 'ubc.jpg',
                 'uqtr.jpg',
                 'usc.jpg',
                 'vanderbilt.jpg',
                 'yale.jpg',   
                ];
